### ISSUE TITLE
Is CrashDebug supported on any CortexM core?

### ISSUE THREAD

**Issue by nordic-krch** [adamgreen/CrashDebug#11]
CrashDebug seems like a great tool and exact what i was looking for post mortem analysis. I am wondering if it is supported on any CortexM? It seems that "Monitor for Remote Inspection" has limited support and i could not find if it is required or an optional feature to run CrashDebug.

I'm using Nordic Semiconductor SoCs (nrf52) which is Cortex M4F with JLink. Is it supported. If not then I would be grateful for tips what is missing to support it.

**Comment by adamgreen** [comment]
CrashDebug itself should work for any ARMv6-M or ARMv7-M based chip, which includes the Cortex-M4F. CrashDebug just uses the MRI core to parse GDB commands. You don't need to worry about MRI itself supporting your device.

@nordic-krch How are you planning to generate the crash dumps for post mortem analysis? If you are using CrashCatcher to produce your crash dump, then you will want to read its documentation to learn how to port it to your particular device.

**Comment by nordic-krch** [comment]
@adamgreen thanks for you answer. I managed to make it working using storing dump from gdb and CrashCatcher (after implementing dumping api).

**Comment by adamgreen** [comment]
> @adamgreen thanks for you answer. I managed to make it working using storing dump from gdb and CrashCatcher (after implementing dumping api).

Excellent!
