### ISSUE TITLE
Generate coredump from thread context

### ISSUE THREAD

**Issue by nordic-krch** [adamgreen/CrashDebug#12]
CrashDebug supports generating crash dump from hardfault interrupt context. However, I would like to dump the context also in case of software error (assert). Any suggestion how that could be added?

**Comment by adamgreen** [comment]
Can you modify your assert handler to generate a hard fault? If you haven't enabled the Debug Monitor exception and no JTAG/SWD debugger is attached then throwing a breakpoint will generate a hard fault:
```c
{ __asm volatile ("bkpt #0"); }
```
[CrashCatcher.h](https://github.com/adamgreen/CrashCatcher/blob/master/include/CrashCatcher.h#L142) also contains some macros like **CRASH_CATCHER_WRITE_FAULT** that can generate memory faults.
