### ISSUE TITLE
Please update .gitmodules

### ISSUE THREAD

**Issue by satirebird** [adamgreen/CrashDebug#13]
Please use the https urls for the submodules:
    `url = https://github.com/adamgreen/mri.git`
instead of 
    `url = git@github.com:adamgreen/mri.git`

**Comment by adamgreen** [comment]
I made them relative so they use whatever type of URL that you use to clone this CrashDebug repository itself.

**Comment by satirebird** [comment]
The same issue exists in your CrashCatcher repo. The submodule points to CrashCatcher at commit [2d04e33](https://github.com/adamgreen/CrashCatcher/commit/2d04e3371f16edde8d0bab1a9a91fbab99ed7819) which has a submodule git@.../gcc4mbed. The recursive clone does not work.

BTW: The tool is great. Thank you very much. It helps a lot.

**Comment by adamgreen** [comment]
@satirebird I think it is fixed now. I had to update CrashCatcher and mri.
