### ISSUE TITLE
Question: Why is gdb needed?

### ISSUE THREAD

**Issue by llllVIIII** [adamgreen/CrashDebug#14]
Hi, 

I realy appreciate your work! Just one question. Why is the GDB needed in combination with the CrashDebug. Shouldn't CrashDebug be able to deduce the stack trace from the elf file?

Can you elaborate futher how GDB and CrashDebug work together?

**Comment by adamgreen** [comment]
The main purpose of CrashDebug is to enable post-mortem debugging. That means more than just getting a call stack. With the CrashDebug/GDB combo you can do anything you could normally do in GDB except for resuming execution or single stepping.

You could write your own tool to use a crash dump and elf file to unwind the stack if that's all you needed.

CrashDebug is a GDB remote stub. That means GDB treats it like it would treat a JTAG debugger. GDB thinks it is connected to a remote target and uses CrashDebug to access the CPU's registers and memory.
