### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by lippit** [adamgreen/CrashDebug#16]
Compiling from latest master, I get the following compile errors:

`Compiling libmocks/tests/printfSpyTest.cpp
In member function ‘char* TEST_GROUP_CppUTestGroupprintfSpy::CreateCheckBuffer(size_t)’,
    inlined from ‘void TEST_GROUP_CppUTestGroupprintfSpy::printfCheckHelloWorldWithBufferOfSize(size_t)’ at libmocks/tests/printfSpyTest.cpp:69:47,
    inlined from ‘virtual void TEST_printfSpy_BufferSize1_Test::testBody()’ at libmocks/tests/printfSpyTest.cpp:86:42:
libmocks/tests/printfSpyTest.cpp:58:16: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated copying 1 byte from a string of length 13 [-Werror=stringop-truncation]
   58 |         strncpy(pCheckString, g_HelloWorld, BufferSize);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In member function ‘char* TEST_GROUP_CppUTestGroupprintfSpy::CreateCheckBuffer(size_t)’,
    inlined from ‘void TEST_GROUP_CppUTestGroupprintfSpy::printfCheckHelloWorldWithBufferOfSize(size_t)’ at libmocks/tests/printfSpyTest.cpp:69:47,
    inlined from ‘virtual void TEST_printfSpy_BufferSize0_Test::testBody()’ at libmocks/tests/printfSpyTest.cpp:80:42:
libmocks/tests/printfSpyTest.cpp:58:16: error: ‘char* strncpy(char*, const char*, size_t)’ destination unchanged after copying no bytes from a string of length 13 [-Werror=stringop-truncation]
   58 |         strncpy(pCheckString, g_HelloWorld, BufferSize);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In member function ‘char* TEST_GROUP_CppUTestGroupprintfSpy::CreateCheckBuffer(size_t)’,
    inlined from ‘void TEST_GROUP_CppUTestGroupprintfSpy::printfCheckHelloWorldWithBufferOfSize(size_t)’ at libmocks/tests/printfSpyTest.cpp:69:47,
    inlined from ‘virtual void TEST_printfSpy_BufferSizeExact_Test::testBody()’ at libmocks/tests/printfSpyTest.cpp:96:42:
libmocks/tests/printfSpyTest.cpp:58:16: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying 13 bytes from a string of the same length [-Werror=stringop-truncation]
   58 |         strncpy(pCheckString, g_HelloWorld, BufferSize);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In member function ‘char* TEST_GROUP_CppUTestGroupprintfSpy::CreateCheckBuffer(size_t)’,
    inlined from ‘void TEST_GROUP_CppUTestGroupprintfSpy::printfCheckHelloWorldWithBufferOfSize(size_t)’ at libmocks/tests/printfSpyTest.cpp:69:47,
    inlined from ‘virtual void TEST_printfSpy_BufferSizeMinus1_Test::testBody()’ at libmocks/tests/printfSpyTest.cpp:91:42:
libmocks/tests/printfSpyTest.cpp:58:16: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated copying 12 bytes from a string of length 13 [-Werror=stringop-truncation]
   58 |         strncpy(pCheckString, g_HelloWorld, BufferSize);
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

My compiler is `gcc version 10.2.1 20200825 [revision c0746a1beb1ba073c7981eb09f55b3d993b32e5c] (SUSE Linux)`
Removing the `-Werror` from the GCCFLAGS allow compilation to finish.

**Comment by adamgreen** [comment]
@lippit I think I have a fix in [the fixIssue16 branch](https://github.com/adamgreen/CrashDebug/tree/fixIssue16). I don't currently have a Linux VM setup to test on. Would you be able to try my proposed fix in that branch?

**Comment by lippit** [comment]
Yes, that compiles fine now! Thanks for the quick fix.

**Comment by adamgreen** [comment]
@lippit Thanks so much for reporting the issue and testing my fix. I will merge into the main branch now.
