### ISSUE TITLE
CrashDebug precompiled binary has dependencies

### ISSUE THREAD

**Issue by felixcollins** [adamgreen/CrashDebug#17]
![image](https://user-images.githubusercontent.com/1680258/127946893-1b26e504-00bd-41cf-9030-639089c7a010.png)

I get this pop up when running gdb with CrashDebug

gdb then runs but no stack or memory regions are available

`
Reading symbols from fw-10143-sensor-hub-stm32-firmware\Debug\THOR_1.5_Sensor_Hub_FW.elf...
Remote debugging using | CrashDebug/CrashDebug --elf fw-10143-sensor-hub-stm32-firmware\Debug\THOR_1.5_Sensor_Hub_FW.elf --dump crash.dmp
Remote communication error.  Target disconnected.: Success.
(gdb) bt
No stack.
(gdb) info mem
Using memory regions provided by the target.
There are no memory regions defined.
(gdb)
`

**Comment by felixcollins** [comment]
I installed mingw and copied the offending dll to the same dir as CrashDebug.exe and the issue went away.

**Comment by adamgreen** [comment]
I have added the missing DLL from the machine on which I built the binary and tested on a clean install of Windows 10.

**Comment by felixcollins** [comment]
Nice one! That was rapid.
