### ISSUE TITLE
CrashDebug seems to hang

### ISSUE THREAD

**Issue by felixcollins** [adamgreen/CrashDebug#18]
I'm working with a crash dump from an STM32H753. I've implemented the HEX dump and saved to a file. Running on windows 10.
I run the gdb with the following command: 
`
C:\ST\STM32CubeIDE_1.6.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.9-2020-q2-update.win32_2.0.0.202105311346\tools\bin\arm-none-eabi-gdb.exe "fw-10143-sensor-hub-stm32-firmware\Debug\THOR_1.5_Sensor_Hub_FW.elf" -ex "set target-charset ASCII" -ex "target remote | CrashDebug/CrashDebug --elf "fw-10143-sensor-hub-stm32-firmware\Debug\THOR_1.5_Sensor_Hub_FW.elf" --dump crash.dmp"
`
The arm gdb cli freezes and will not respond to ctrl-c or anything else. 

I built CrashDebug locally and ran again, then attached GDB (mingw) to the CrashDebug process. I can not get symbols to load properly for some reason. When I interrupted the process this is the state of the threads.

`
(gdb) symbol-file c:/users/felix/source/Thor/CrashDebug/bins/win32/CrashDebug.exe
Load new symbol table from "c:\users\felix\source\Thor\CrashDebug\bins\win32\CrashDebug.exe"? (y or n) y
Reading symbols from c:\users\felix\source\Thor\CrashDebug\bins\win32\CrashDebug.exe...done.
(gdb) thread apply all bt

Thread 2 (Thread 3240.0x2804):
#0  0x77154d11 in ntdll!DbgBreakPoint () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x7718dca9 in ntdll!DbgUiRemoteBreakin () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0xaa43fb20 in ?? ()
#3  0x7718dc70 in ntdll!DbgUiIssueRemoteBreakin () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x7556fa29 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#5  0x77147a7e in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x77147a4e in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#7  0x00000000 in ?? ()

Thread 1 (Thread 3240.0xfc4):
#0  0x77152a1c in ntdll!ZwWriteFile () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x7509f32c in WriteFile () from C:\WINDOWS\System32\KernelBase.dll
#2  0x00000134 in ?? ()
#3  0x00000000 in ?? ()
(gdb)
`

Any ideas what I'm doing wrong?

**Comment by felixcollins** [comment]
If you want the hex dump and the .elf file let me know.

**Comment by felixcollins** [comment]
Crash file and .elf.
Crash file has the entire ram segment that hosts the heap. Running freertos so task stacks should be allocated in the heap I think.
[crash.zip](https://github.com/adamgreen/CrashDebug/files/6921000/crash.zip)
[THOR_1.5_Sensor_Hub_FW.elf.zip](https://github.com/adamgreen/CrashDebug/files/6921007/THOR_1.5_Sensor_Hub_FW.elf.zip)

**Comment by felixcollins** [comment]
Oh, BTW the crash in this case was a test of the system triggered by dereferencing 0xFFFFFFFF.

**Comment by adamgreen** [comment]
Thanks for reporting and sorry I was a bit sluggish to start looking into this issue.

I have reproduced your problem on Windows 10 and verified that the files you provided above do work when I use CrashDebug on macOS. Hopefully I can get to the bottom of this issue in the next day or so.

**Comment by adamgreen** [comment]
@felixcollins Try using the following command line instead:
```
C:\ST\STM32CubeIDE_1.6.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.9-2020-q2-update.win32_2.0.0.202105311346\tools\bin\arm-none-eabi-gdb.exe "fw-10143-sensor-hub-stm32-firmware\Debug\THOR_1.5_Sensor_Hub_FW.elf" -ex "set target-charset ASCII" -ex "target remote | CrashDebug/CrashDebug --elf "fw-10143-sensor-hub-stm32-firmware/Debug/THOR_1.5_Sensor_Hub_FW.elf" --dump crash.dmp"
```
The only difference is that the paths in the CrashDebug command line are all forward slashes ('/') instead of backslashes ('\'). I suspect that GDB treats it as an escape character instead of a Windows path separator.

I am going to keep this bug open to see if there is a way that I can stop the hang from happening and hopefully inform the user that the command line parameters were incorrect.

**Comment by adamgreen** [comment]
It looks like writing all of the error and usage output to stderr instead of stdout gets the correct behavior so that is what I will do in a future commit. I will also add a note to the README highlighting this quirk for Windows users.

**Comment by felixcollins** [comment]
Thanks so much Adam. I really appreciate it. I was looking at having to whip up a quick custom crash dump. Your solution is so much better than what I would have put together. Sorry to make you get on a windows machine! It is such a pain the whole path separator thing. One would think it would have been sorted out properly by now...

**Comment by adamgreen** [comment]
I have pushed up a change which will make this type of problem much easier to diagnose in the future. I have also added a note at the end of the README warning Windows users about the slash issue.

Thanks again for reporting. Much appreciated.

**Comment by felixcollins** [comment]
Is there any way to run CrashDebug seperately to gdb and connect once it is running?  If not... how do you go about debugging?

**Comment by adamgreen** [comment]
I used Task Manager to get the process ID for the CrashCatcher spawned by GDB and then attached to that PID.
