### ISSUE TITLE
One stupid question, why not generate standard gdb core file(like the x86 Linux PC)?

### ISSUE THREAD

**Issue by swordligit** [adamgreen/CrashDebug#5]
so I can debug with the simple command like
```
arm-none-eabi-gdb  xxx.elf corefile
```

**Comment by adamgreen** [comment]
When I originally wrote CrashDebug, I couldn't find anything about the format required for this. Later I tried stepping through the arm-none-eabi-gdb code when loading such a corefile for a Cortex-M part and I got to a point where it should start loading the corefile and there seemed to be no code in GDB to complete the load for these microcontrollers. From the notes that I took at the time (July 2017):
> It then fails in sniff_core_bfd() since there are no registered sniffers in arm-none-eabi-gdb.

So as far as I can tell, GDB doesn't support core files for bare metal code on Cortex-M microcontrollers. If you find something different then please let me know.

**Comment by swordligit** [comment]
Thanks for describing the background and your fantastic work.
If I find more info, will let you know.
