### ISSUE TITLE
Is it possible to support threads?

### ISSUE THREAD

**Issue by swordligit** [adamgreen/CrashDebug#7]
Some times it is useful for knowing the information of thread,
and the callback of one threads..

**Comment by adamgreen** [comment]
It's possible but not something that I am likely to attempt adding in the near future as it is probably more work than the total work I have already put into CrashDebug to date. There are many things that I would have to figure out before I could add such a feature:
* What RTOSs are to be supported and how would I test them?
* Should the support for the various RTOSs be statically linked into CrashDebug like OpenOCD?
* Or should the support for the needed RTOS be dynamically linked in at runtime like the JLink GDB Server?
* How to architect it into the existing MRI core that I use for GDB interfacing.

When using ARM's RTX RTOS in the past, I haven't bothered with the official GDB thread support. Instead I have just written GDB user defined commands to give me the ability to look into the individual thread states. The advantage of this approach is that it worked with various debug stub solutions: OpenOCD, JLink, my own CrashDebug and MRI debug stubs, etc. My RTX/newlib commands can be found [here](https://github.com/adamgreen/gcc4mbed/blob/feature/newlibThreadSafetyMaster/samples/gdbinit).

**Comment by swordligit** [comment]
Understand.
Your gcc4mbed seems a good method to know the state
of the thread,  will have a try, thanks a lot.

**Comment by adamgreen** [comment]
> Your gcc4mbed seems a good method to know the state of the thread, will have a try, thanks a lot.

At least it shows the idea. You would need to re-implement for your RTOS.

I am reopening this issue as it is something that can be considered for the future.

**Comment by swordligit** [comment]
Now I am using the FreeRTOS and RTX, so the **gcc4mbed**
make sense for me.
As for the RTOS used for arm Cortex_M series, is it possible
just using their CMSIS layer? This layer is above the RTX or
FreeRTOS.
https://github.com/ARM-software/CMSIS_5

**Comment by swordligit** [comment]
@adamgreen ，How about this issue? If you have any progress, 
I can test them.

**Comment by adamgreen** [comment]
I won't be working on RTOS support anytime soon. The surface area is just too large as there are so many RTOS options available, I don't know which ones are the most important to support, and I don't personally need such support so it is an itch that I don't need to scratch.

If I was going to build a RTOS solution at all, I probably wouldn't add it to CrashDebug anyway. I would instead write a GDB server similar to CrashDebug that only supported the thread specific GDB commands. This RTOS aware GDB server would use a socket, serial port, or pipes to connect to a non-RTOS aware GDB server such as CrashDebug. It would just pass non-RTOS GDB commands along to this server and utilize its abilities to read memory/registers to provide the additional thread command support. The advantage of such a solution is that it would work with various non-RTOS aware GDB servers that already exist such as CrashDebug, MRI, OpenOCD, JLinkGDBServer, etc. Even though some of those GDB servers already have RTOS support they may not support a particular type and/or version.
