### ISSUE TITLE
commit message typo error

### ISSUE THREAD

**Issue by swordligit** [adamgreen/CrashDebug#8]
> Update **Linus** binary to 1.6-20190624.0

should be

> Update **Linux** binary to 1.6-20190624.0?

Another issue is about the coding style, all the files(source file and
Makefiles) is ended with **\r\n**, which will show a **^M** in linux or when
using git diff, could you change the style. but anyway, this is not the big
problem.

**Comment by adamgreen** [comment]
Sucks about the typo but it isn't good to update a commit after pushing to a public master branch.

The Windows line endings are by design.
